package com.gotc.util;

/**
 * Created by srikaram on 06-Nov-16.
 */
public interface Dialogues {

    String PARSEERROR = "IF YOU THINK THIS HAS A HAPPY ENDING, YOU HAVEN’T BEEN PAYING ATTENTION";
    String BEGINCLASS = "WINTER IS COMING";
    String BEGINMAIN = "VALAR DOHAERIS";
    String MINUSOPERATOR = "STAY LOW";
    String ENDCLASS = "MY WATCH HAS ENDED";
    String ENDMAIN = "VALAR MORGHULIS";
    String PRINT = "LET ME SEE IT ONE MORE TIME";
    String EQUALTO = "I AM YOURS AND YOU ARE MINE";
    String FALSE = "YOU KNOW NOTHING";
    String ELSE = "SHAME";
    String WHILE = "MY REIGN HAS JUST BEGUN";
    String ENDWHILE = "TURN US AWAY, AND WE WILL BURN YOU FIRST";
    String DECLAREMETHOD = "FORGET THE BLOODY GODS AND LISTEN TO WHAT I'M TELLING YOU";
    String METHODARGUMENTS = "LANNISTERS SEND THEIR REGARDS";
    String RETURN = "GET OUT, YOU HATEFUL BITCH";
    String CALLMETHOD = "WHERE IS THE GOD OF TITS AND WINE";
    String ASSIGNVARIABLEFROMMETHODCALL = "I DRINK AND I KNOW THINGS";
    String ASSIGNVARIABLE = "THE NORTH REMEMBERS";
    String NOT = "KILL THE BOY";
    String ENDMETHODDECLARATION = "I'M GOING HOME";
    String AND = "WE STAND TOGETHER";
    String DIVISIONOPERATOR = "ANYONE CAN BE KILLED";
    String TRUE = "HODOR";
    String NONVOIDMETHOD = "THERE'S NO CURE FOR BEING A CUNT";
    String ENDIF = "FUCK OFF";
    String MULTIPLICATIONOPERATOR = "YOU GOT FAT";
    String LESSERTHAN = "YOU HAVE LESS HONOR THAN A BACK ALLEY WHORE";
    String PLUSOPERATOR = "GIVE MY REGARDS TO THE NIGHT’S WATCH";
    String OR = "YOU WIN OR YOU DIE";
    String IF = "ARE YOU A VIRGIN";

}
